name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Update system
      run: sudo apt update -y
    - name: Install libev
      run: sudo apt install -y libev4 libev-dev
    - name: Install gcc-9
      run: sudo apt install -y gcc-9
    - name: Update alternatives
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60
    - name: mkdir
      run: mkdir build
      working-directory: /home/runner/work/pgprtdbg/pgprtdbg/
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
      working-directory: /home/runner/work/pgprtdbg/pgprtdbg/build/
    - name: make
      run: make
      working-directory: /home/runner/work/pgprtdbg/pgprtdbg/build/
